image: node:latest

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
  tags:
    - gitlab-org

test_with_lab:
  stage: test
  script: npm test
  tags:
    - gitlab-org

deploy_to_elb:
  stage: deploy
  script:
    - ./bin/deploy.sh
  tags:
    - gitlab-org