language: node_js
node_js: 
  - "7"
install:
  - npm install

cache:
  directories:
    - "node_modules"

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  skip_cleanup: true
  region: "us-east-2"
  app: "accounts.tcff.co"
  env: "tcf-accounts-main"
  bucket_name: tcf-accounts-main-bucket

notifications:
  slack: thecreativefoundation:n3PZ4D7QrW3uXjH7QdBH5exQ
  on_failure: always
  on_success: always